name: José M. Pérez
description: A description for your blog
url: http://jmperezperez.com
markdown: redcarpet
pygments: true
permalink: /:title
paginate: 5
paginate_path: "page:num"
timezone: Europe/Madrid
