name: José M. Pérez
description: JMPerez Blog
url: https://jmperezperez.com
enforce_ssl: jmperezperez.com
markdown: redcarpet
pygments: true
permalink: /:title
paginate: 5
paginate_path: "page:num"
timezone: Europe/Madrid
